# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: sooth 2.1.0 ruby lib
# stub: ext/sooth_native/extconf.rb

Gem::Specification.new do |s|
  s.name = "sooth".freeze
  s.version = "2.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Jason Hutchens".freeze]
  s.date = "2017-04-17"
  s.description = "Sooth is a simple stochastic predictive model.".freeze
  s.email = "jasonhutchens@gmail.com".freeze
  s.extensions = ["ext/sooth_native/extconf.rb".freeze]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "CHANGELOG.md",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "UNLICENSE",
    "VERSION",
    "ext/sooth_native/extconf.rb",
    "ext/sooth_native/native.c",
    "ext/sooth_native/sooth_context.h",
    "ext/sooth_native/sooth_predictor.c",
    "ext/sooth_native/sooth_predictor.h",
    "ext/sooth_native/sooth_statistic.h",
    "lib/sooth.rb",
    "sooth.gemspec",
    "spec/memory_spec.rb",
    "spec/predictor_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/jasonhutchens/sooth".freeze
  s.licenses = ["UNLICENSE".freeze]
  s.required_ruby_version = Gem::Requirement.new("~> 2.1".freeze)
  s.rubygems_version = "2.6.8".freeze
  s.summary = "Sooth is a simple stochastic predictive model.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>.freeze, ["~> 3.1"])
      s.add_development_dependency(%q<yard>.freeze, ["~> 0.8"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 4.1"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.7"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.0"])
      s.add_development_dependency(%q<simplecov>.freeze, ["~> 0.9"])
      s.add_development_dependency(%q<byebug>.freeze, ["~> 8.2"])
      s.add_development_dependency(%q<rake-compiler>.freeze, ["~> 0.9"])
      s.add_development_dependency(%q<github_changelog_generator>.freeze, ["~> 1.14"])
    else
      s.add_dependency(%q<rspec>.freeze, ["~> 3.1"])
      s.add_dependency(%q<yard>.freeze, ["~> 0.8"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 4.1"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.7"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.0"])
      s.add_dependency(%q<simplecov>.freeze, ["~> 0.9"])
      s.add_dependency(%q<byebug>.freeze, ["~> 8.2"])
      s.add_dependency(%q<rake-compiler>.freeze, ["~> 0.9"])
      s.add_dependency(%q<github_changelog_generator>.freeze, ["~> 1.14"])
    end
  else
    s.add_dependency(%q<rspec>.freeze, ["~> 3.1"])
    s.add_dependency(%q<yard>.freeze, ["~> 0.8"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 4.1"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.7"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.0"])
    s.add_dependency(%q<simplecov>.freeze, ["~> 0.9"])
    s.add_dependency(%q<byebug>.freeze, ["~> 8.2"])
    s.add_dependency(%q<rake-compiler>.freeze, ["~> 0.9"])
    s.add_dependency(%q<github_changelog_generator>.freeze, ["~> 1.14"])
  end
end

